version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/user/src/app
    # Add other configurations as needed

  postgres:
    image: postgres
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    # Add other configurations as needed
volumes:
  data: {}